- name: html to pdf
  uses: fifsky/html-to-pdf-action@master
  with:
    htmlFile: ./public/index.html
    outputFile: ./public/resume.pdf
    pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
